version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true  # Enable file watching in Docker
    stdin_open: true  # Keep stdin open for development
    tty: true        # Allocate a pseudo-TTY